site_name: Iris' Blogs
theme: 
  name: material
  logo: assets/avatar.jpg
  favicon: assets/favicon.jpg
nav:
  - 'ğŸ  Home': index.md
  - 'ğŸ“° New tech':
    - Claude Skill: ğŸ”§ æ–°æŠ€æœ¯/Claude-Skill.md
  - 'ğŸ Python':
    - schedule-è®¡åˆ’ä»»åŠ¡: ğŸ Python/py-schedule.md
    - AgenticRAG-paradigm: ğŸ Python/AgenticRAG-paradigm.md
  - 'ğŸ¦œ LangChain':
    - ç»„ä»¶æ¶æ„: ğŸ¦œ LangChain/LangChain ç»“æ„è§£æï¼ˆ1ï¼‰ï¼šç»„ä»¶æ¶æ„.md
    - RAGä¿¡æ¯å¤„ç†æŠ€æœ¯: ğŸ¦œ LangChain/LangChain-RAGä¿¡æ¯å¤„ç†æŠ€æœ¯è§£æ.md
    - LC-è®°å¿†åŠŸèƒ½: ğŸ¦œ LangChain/LC-Memory.md
    - Runnablesæ¥å£è§£æ: ğŸ¦œ LangChain/Runnablesæ¥å£è§£æ.md
  - 'ğŸ“¦ Prompts':
    - Cursor Rules å¼€å‘è€…æ¨¡æ¿: ğŸ“¦ prompts/cursorruleså¼€å‘è€…æ¨¡æ¿.md
    - æç¤ºè¯å·¥ç¨‹: ğŸ“¦ prompts/æç¤ºè¯å·¥ç¨‹.md
  - 'ğŸ”§ Tools':
    - YAMLåŸºæœ¬è¯­æ³•: yamlåŸºæœ¬è¯­æ³•.md
  - 'ğŸ’¡ å…¶ä»–æŠ€æœ¯':
    - Linux Crontab è®¡åˆ’ä»»åŠ¡: ğŸ’¡å…¶ä»–æŠ€æœ¯/linux-crontabè®¡åˆ’ä»»åŠ¡.md
  - 'ğŸ‘¤ About': about.md
