site_name: Iris' Blogs
theme: 
  name: material
  logo: assets/avatar.jpg
  favicon: assets/favicon.jpg
nav:
  - 'ğŸ  Home': index.md
  - 'ğŸ¦œ LangChain':
    - ç»„ä»¶æ¶æ„: ğŸ¦œ LangChain/LangChain ç»“æ„è§£æï¼ˆ1ï¼‰ï¼šç»„ä»¶æ¶æ„.md
    - RAGä¿¡æ¯å¤„ç†æŠ€æœ¯: ğŸ¦œ LangChain/LangChain-RAGä¿¡æ¯å¤„ç†æŠ€æœ¯è§£æ.md
    - Runnablesæ¥å£: ğŸ¦œ LangChain/LC-Runnablesæ¥å£è§£æ.md
  - 'ğŸ“¦ Prompts':
    - Cursor Rules å¼€å‘è€…æ¨¡æ¿: ğŸ“¦ prompts/cursorruleså¼€å‘è€…æ¨¡æ¿.md
  - 'ğŸ‘¤ About': about.md
