[project]
name = "blogs"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "loguru>=0.7.3",
    "mkdocs>=1.6.1",
    "mkdocs-material>=9.7.1",
    "schedule>=1.2.2",
]
